
package pbo;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import java.util.Random;
import javafx.scene.layout.Background;
import javax.swing.Timer;

public class newGamePanel extends javax.swing.JPanel {

    ArrayList<Bangun> arr = new ArrayList<>();
    public newGamePanel() {
        initComponents();
        setFocusable(true);// utk deteksi key pressed pada panel
    }

    @Override
    protected void paintComponent(Graphics grphcs) {
        super.paintComponent(grphcs);
        Graphics2D g2 = (Graphics2D) grphcs;
        for (Bangun b : arr) {
            g2.drawString(b.getKarakter()+"",b.getX(),b.getY());
            if ( b instanceof Kotak){
                Rectangle2D kotak = new Rectangle2D.Double(b.getX(),b.getY(),50,50);
                g2.setColor(b.getWarna());
                g2.fill(kotak);
            }
            else if ( b instanceof Lingkaran){
                Ellipse2D lingkaran = new Ellipse2D.Double(b.getX(),b.getY(),50,50);
                g2.setColor(b.getWarna());
                g2.fill(lingkaran);
            }
        }
        //g2.setColor(Color.blue);
        /*Random r = new Random();
        Color c = new Color(r.nextInt(255),
            r.nextInt(255),r.nextInt(255));
        g2.setColor(c);
        if ( kotak.isSelected()){
            Rectangle2D kotak = new Rectangle2D.Double(100,100,50,50);
            g2.draw(kotak);
            g2.fill(kotak);
        }
        else if ( lingkaran.isSelected()){
            Ellipse2D lingkaran = new Ellipse2D.Double(100,100,50,50);
            g2.draw(lingkaran);
            g2.fill(lingkaran);
        }*/
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        kotak = new javax.swing.JRadioButton();
        lingkaran = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(kotak);
        kotak.setSelected(true);
        kotak.setText("kotak");
        kotak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kotakActionPerformed(evt);
            }
        });
        add(kotak, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 46, -1, -1));

        buttonGroup1.add(lingkaran);
        lingkaran.setText("lingkaran");
        lingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lingkaranActionPerformed(evt);
            }
        });
        add(lingkaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 46, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jButton1.setText("start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void kotakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kotakActionPerformed
        repaint();
        this.requestFocus();
    }//GEN-LAST:event_kotakActionPerformed

    private void lingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lingkaranActionPerformed
        repaint();
        this.requestFocus(); // pindahkan fokus ke panel agar bs deteksi key pressed
    }//GEN-LAST:event_lingkaranActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        Random r = new Random();
        Color c = new Color(r.nextInt(255),
            r.nextInt(255),r.nextInt(255));
        if ( kotak.isSelected()){
            arr.add( new Kotak(evt.getX(),evt.getY(),50,50,c,(char)(arr.size()+'0')));
        }
        else{
            arr.add( new Lingkaran(evt.getX(),evt.getY(),50,50,c,(char)(arr.size()+'0')));
        }
        repaint();
    }//GEN-LAST:event_formMouseClicked

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if ( evt.getKeyChar()=='x'){
            arr.remove(arr.size()-1);
            repaint();
        }
    }//GEN-LAST:event_formKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Timer t = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                jLabel1.setText(String.valueOf(Integer.parseInt(jLabel1.getText())+1));
                for (Bangun b : arr) {
                    b.gerak();
                }
                repaint();
            }
        });
        jLabel1.setText("0");
        t.start();
        this.requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton kotak;
    private javax.swing.JRadioButton lingkaran;
    // End of variables declaration//GEN-END:variables
}
