/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihanuasno3;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.Ellipse2D;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author asus_
 */
public class panel extends javax.swing.JPanel {

    /**
     * Creates new form panel
     */
    
    boolean move=true;
    ArrayList<enemy> enemies=new ArrayList<>();
    pacman p=new pacman();
    public panel() {
        initComponents();
        setBounds(0, 0, 800, 600);
        setFocusable(true);
        this.add(p.getLabelP());
        p.setArah(3);
        for (int i = 0; i < 5; i++) {
            int randx=(int) (Math.random()*750);
            int randy=(int) (Math.random()*550);
            enemies.add(new enemy(randx, randy, 20, 20, Color.black));
        }
        p.setE(enemies);
        p.start();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2=(Graphics2D)g;
        for (int i = 0; i < enemies.size(); i++) {
            Ellipse2D musuh=new Ellipse2D.Double(enemies.get(i).getX(), enemies.get(i).getY(), 20, 20);
            g2.fill(musuh);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        char input=evt.getKeyChar();
        if(input=='w'){
            p.setArah(0);
        }
        else if(input=='a'){
            p.setArah(1);
        }
        else if(input=='s'){
            p.setArah(2);
        }
        else if(input=='d'){
            p.setArah(3);
        }
    }//GEN-LAST:event_formKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
