/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihanuasno2;

import java.awt.Color;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 *
 * @author asus_
 */
public class panel extends javax.swing.JPanel {

    /**
     * Creates new form panel
     */
    public panel() {
        initComponents();
        this.setBounds(0, 0, 500, 300);
        redButton.setSize(20, 20);
        redButton.setBackground(Color.red);
        setFocusable(true);
        loadButton.setFocusable(false);
        redButton.setFocusable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadButton = new javax.swing.JButton();
        redButton = new javax.swing.JButton();

        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        loadButton.setText("load");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(loadButton)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(redButton)
                .addContainerGap(318, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(loadButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(redButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        char input=evt.getKeyChar();
        if(input=='w'&&redButton.getY()>0){
            redButton.setLocation(redButton.getX(), redButton.getY()-5);
        }
        else if(input=='s'&&redButton.getY()<270){
            redButton.setLocation(redButton.getX(), redButton.getY()+5);
        }
        else if(input=='a'&&redButton.getX()>0){
            redButton.setLocation(redButton.getX()-5, redButton.getY());
        }
        else if(input=='d'&&redButton.getX()<465){
            redButton.setLocation(redButton.getX()+5, redButton.getY());
        }
    }//GEN-LAST:event_formKeyPressed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        // TODO add your handling code here:
        ArrayList<balokHalangan> inBlocks = null;
        try {
            ObjectInputStream filein=new ObjectInputStream(new FileInputStream("halangan.txt"));
            inBlocks=(ArrayList<balokHalangan>)filein.readObject();
            filein.close();
        } catch (IOException ex) {
            System.out.println("error");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(panel.class.getName()).log(Level.SEVERE, null, ex);
        }
        ArrayList<JButton> blueButtons=new ArrayList<>();
        for (int i = 0; i < inBlocks.size(); i++) {
            blueButtons.add(new JButton());
            blueButtons.get(i).setBounds(inBlocks.get(i).getPosx(), 
                    inBlocks.get(i).getPosy(), inBlocks.get(i).getUkuran(), 
                    inBlocks.get(i).getUkuran());
            blueButtons.get(i).setBackground(Color.blue);
            blueButtons.get(i).setForeground(Color.white);
            blueButtons.get(i).setText(String.valueOf(i));
            this.add(blueButtons.get(i));
            this.repaint();
            System.out.println("button added");
        }
    }//GEN-LAST:event_loadButtonActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton loadButton;
    private javax.swing.JButton redButton;
    // End of variables declaration//GEN-END:variables
}
