/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication49;

import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.paint.Color;
import static javafx.scene.paint.Color.rgb;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Daniel_DS
 */

public class batlle extends javax.swing.JPanel {
    
    public batlle() {
        initComponents();
        start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        g_pokemon_Sendiri = new javax.swing.JLabel();
        g_pokemon = new javax.swing.JLabel();
        nama_musuh = new javax.swing.JLabel();
        skill1 = new javax.swing.JLabel();
        skill2 = new javax.swing.JLabel();
        skill3 = new javax.swing.JLabel();
        skill4 = new javax.swing.JLabel();
        pointer = new javax.swing.JLabel();
        hp_musuh_bars = new javax.swing.JLabel();
        nama_pokemon_sendiri = new javax.swing.JLabel();
        level_pokemon_sendiri = new javax.swing.JLabel();
        hp_sendiri_bars = new javax.swing.JLabel();
        hp_sendiri = new javax.swing.JProgressBar();
        stats_sendiiri = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nav_keterangan = new javax.swing.JLabel();
        back_panel = new javax.swing.JLabel();
        hp_musuh = new javax.swing.JProgressBar();
        nama_pokemon_musuh = new javax.swing.JLabel();
        status_musuh = new javax.swing.JLabel();
        skill = new javax.swing.JLabel();
        nav = new javax.swing.JLabel();
        tanah_sendiri = new javax.swing.JLabel();
        tanah_lawan = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(576, 480));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        g_pokemon_Sendiri.setText("jLabel1");
        add(g_pokemon_Sendiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        g_pokemon.setText("jLabel1");
        add(g_pokemon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        nama_musuh.setText("jLabel1");
        add(nama_musuh, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        skill1.setFont(new java.awt.Font("Pokemon Fire Red", 0, 30)); // NOI18N
        skill1.setText(" ");
        add(skill1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 247, 130, 40));

        skill2.setFont(new java.awt.Font("Pokemon Fire Red", 0, 30)); // NOI18N
        skill2.setText(" ");
        add(skill2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 110, 40));

        skill3.setFont(new java.awt.Font("Pokemon Fire Red", 0, 30)); // NOI18N
        skill3.setText(" ");
        add(skill3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 207, 130, 40));

        skill4.setFont(new java.awt.Font("Pokemon Fire Red", 0, 30)); // NOI18N
        skill4.setText(" ");
        add(skill4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 147, 120, 70));

        pointer.setText(" ");
        add(pointer, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 90, 60));

        hp_musuh_bars.setText("jLabel1");
        add(hp_musuh_bars, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));

        nama_pokemon_sendiri.setFont(new java.awt.Font("Pokemon Fire Red", 0, 32)); // NOI18N
        nama_pokemon_sendiri.setForeground(new java.awt.Color(38, 46, 46));
        add(nama_pokemon_sendiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 110, 10));

        level_pokemon_sendiri.setFont(new java.awt.Font("Pokemon Fire Red", 0, 32)); // NOI18N
        level_pokemon_sendiri.setForeground(new java.awt.Color(38, 46, 46));
        add(level_pokemon_sendiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 110, 10));
        add(hp_sendiri_bars, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 70, 30));

        hp_sendiri.setBackground(new java.awt.Color(38, 46, 46));
        hp_sendiri.setForeground(new java.awt.Color(112, 249, 168));
        hp_sendiri.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(hp_sendiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, -1));

        stats_sendiiri.setText(" ");
        add(stats_sendiiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 70, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        nav_keterangan.setBackground(new java.awt.Color(255, 255, 255));
        nav_keterangan.setFont(new java.awt.Font("Pokemon Fire Red", 1, 32)); // NOI18N
        nav_keterangan.setForeground(new java.awt.Color(255, 255, 255));

        back_panel.setFont(new java.awt.Font("Pokemon Fire Red", 1, 24)); // NOI18N
        back_panel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                back_panelKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(nav_keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(back_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(nav_keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(back_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 570, 70));

        hp_musuh.setBackground(new java.awt.Color(38, 46, 46));
        hp_musuh.setForeground(new java.awt.Color(112, 249, 168));
        hp_musuh.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(hp_musuh, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        nama_pokemon_musuh.setFont(new java.awt.Font("Pokemon Fire Red", 0, 32)); // NOI18N
        add(nama_pokemon_musuh, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 50, 30));

        status_musuh.setText("jLabel1");
        add(status_musuh, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        skill.setText(" ");
        add(skill, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));
        add(nav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 406, 575, 74));

        tanah_sendiri.setText(" ");
        add(tanah_sendiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 54, -1, -1));
        add(tanah_lawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 113, -1, -1));
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 0, -1, 480));
    }// </editor-fold>//GEN-END:initComponents
    int i=0;
    
      pokemon[] mypokemon = new pokemon[6];
      pokemon musuh = new ccharmander();
      int pilihan =0;
      String[] nm_skill;
      int[] mp_skill;
      int[] maxmp_skill;
      ArrayList<String> kata =new ArrayList<String>();
      
    private void start()
    {
        File font_file = new File("Fonts/pokemon_fire_red.ttf");
        
        mypokemon[0] = new cpikachu();
        nm_skill=mypokemon[pilihan].getSkill();
        mp_skill=mypokemon[pilihan].getMp();
        maxmp_skill = mypokemon[pilihan].getMaxmp();
        this.setSize(576,480);
        this.setLayout(null);
        ImageIcon back = new ImageIcon("images/background.PNG");
        ImageIcon navs = new ImageIcon("images/menu_battle.PNG");
        ImageIcon po = new ImageIcon("images/pointer.PNG");
        ImageIcon ts = new ImageIcon("images/tanah_sendiri.PNG");
        ImageIcon tm  = new ImageIcon("images/tanah_lawan.PNG");
        ImageIcon sk  = new ImageIcon("images/skill_menu.PNG");
        ImageIcon stats_s  = new ImageIcon("images/status_sendiri.PNG");
        ImageIcon keterangan  = new ImageIcon("images/message_board.PNG");
        ImageIcon stast_m  = new ImageIcon("images/status.PNG");
        ImageIcon hp_sendiri_bar  = new ImageIcon("images/hp_bar.PNG");
        ImageIcon hp_musuh_bar  = new ImageIcon("images/hp_bar_musuh.PNG");
        ImageIcon icon_musuh = new ImageIcon("images/bulba.PNG");

        g_pokemon.setSize(95,95);
        karakter(musuh.getNama(),2);
        g_pokemon.setLocation(380,80);
        g_pokemon_Sendiri.setSize(155,105);
        karakter(mypokemon[pilihan].getNama(),1);
        g_pokemon_Sendiri.setLocation(50,225);
        jPanel1.setVisible(true);
        jPanel1.setSize(576,111);
        background.setIcon(back);
        background.setSize(576,480);
        
        nav.setIcon(navs);
        nav.setSize(566,111); 
        nav.setLocation(0, 330);
        
        tanah_sendiri.setIcon(ts);
        tanah_sendiri.setSize(327,57);
        tanah_sendiri.setLocation(0, 273);
        
        tanah_lawan.setIcon(tm);
        tanah_lawan.setSize(327,88);
        tanah_lawan.setLocation(300, 125);
        // menu 1 : (304,355)
        // menu 2 : (304,390)
        // menu 3 : (430,393)
        // menu 4 : (430,355)
        pointer.setIcon(po);
        pointer.setSize(20,30);
        pointer.setLocation(304,355);
        
        skill.setIcon(sk);
        skill.setSize(566,111); 
        skill.setLocation(0, 330);
        
        
        //--resize--
            Image stats_s2 = stats_s.getImage();
            Image new_image = stats_s2.getScaledInstance(283, 90, java.awt.Image.SCALE_SMOOTH);
            stats_s = new ImageIcon(new_image);
        //-----------
        
        stats_sendiiri.setIcon(stats_s);
        stats_sendiiri.setSize(293,101);
        stats_sendiiri.setLocation(270, 234);
        
        status_musuh.setIcon(stast_m);
        status_musuh.setSize(293,101);
        status_musuh.setLocation(20, 50);
    
        nama_pokemon_sendiri.setText(mypokemon[pilihan].getNama());
        nama_pokemon_sendiri.setSize(200,100);
        nama_pokemon_sendiri.setLocation(300,210);
        
        level_pokemon_sendiri.setText("Lv"+mypokemon[pilihan].getLevel());
        level_pokemon_sendiri.setSize(200,100);
       level_pokemon_sendiri.setLocation(500,210);
        
        
        
        hp_sendiri.setSize(130,14);
        hp_sendiri.setValue(100);
        hp_musuh.setSize(248,14);
        hp_musuh.setValue(100);
        this.setFocusable(true);
        
        //skill
        
        skill1.setText(nm_skill[0]);
        skill1.setSize(100,100);
        skill1.setLocation(70, 315);
        skill2.setText(nm_skill[1]);
        skill2.setSize(100,100);
        skill2.setLocation(70, 350);
        skill3.setText(nm_skill[2]);
        skill3.setSize(100,100);
        skill3.setLocation(220, 315);
        skill4.setText(nm_skill[3]);
        skill4.setSize(100,100);
        skill4.setLocation(220, 350);
        jPanel1.setLocation(0,330);
        jPanel1.setVisible(false);
        nav_keterangan.setVisible(false);
        
        back_panel.setIcon(keterangan);
        back_panel.setSize(566,70);
        
        //hp_sendiri
        hp_sendiri_bars.setIcon(hp_sendiri_bar);
        hp_sendiri_bars.setSize(137,17);
        hp_sendiri_bars.setLocation(400, 278);
        hp_sendiri.setLocation(402,279);
        hp_sendiri.setSize(132,14);
        hp_musuh_bars.setIcon(hp_musuh_bar);
        hp_musuh_bars.setSize(137,17);
        hp_musuh_bars.setLocation(143, 102);
        hp_musuh.setLocation(143,102);
        hp_musuh.setSize(133,16);
        //musuh
        nama_pokemon_musuh.setText(musuh.getNama());
        nama_pokemon_musuh.setSize(200,100);
        nama_pokemon_musuh.setLocation(40,35);
        //visible
        show_skill(false);
        skill_nav(false);
        g=true;
        gerak();
        
    }
    //private void 
    boolean g;
    public void gerak()
    {
         try {
                            Thread.sleep(100);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(batlle.class.getName()).log(Level.SEVERE, null, ex);
                        }
        Thread t1 = new Thread(){
            
            public void run() {
                do
                {
                    for (int j = stats_sendiiri.getY(); j > 228; j--) {
                        try {
                            Thread.sleep(100);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(batlle.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        stats_sendiiri.setLocation(stats_sendiiri.getX(),j);
                    }
                    for (int j = 228; j < 234; j++) {
                        try {
                            Thread.sleep(80);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(batlle.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        stats_sendiiri.setLocation(stats_sendiiri.getX(),j);
                    } 
                }while(g);
                
            }
        };
        if(g)
        {
             t1.start();
        }
        
    }
    private void karakter(String nama,int flags)
    {
        System.out.println("Tipe : "+flags);
        System.out.println("Nama : "+nama);
        ImageIcon Bulbasaur  = new ImageIcon("images/Front/1.PNG");
        ImageIcon Ivysaur  = new ImageIcon("images/Front/2.PNG");
        ImageIcon Charmander  = new ImageIcon("images/Front/4.PNG");
        ImageIcon Charmeleon  = new ImageIcon("images/Front/5.PNG");
        ImageIcon Squirtle  = new ImageIcon("images/Front/7.PNG");
        ImageIcon Wartortle  = new ImageIcon("images/Front/8.PNG");
        ImageIcon Caterpie  = new ImageIcon("images/Front/10.PNG");
        ImageIcon Metapod  = new ImageIcon("images/Front/11.PNG");
        ImageIcon Weedle  = new ImageIcon("images/Front/13.PNG");
        ImageIcon Kakuna  = new ImageIcon("images/Front/14.PNG");
        ImageIcon Pidgey  = new ImageIcon("images/Front/16.PNG");
        ImageIcon Pidgeotto  = new ImageIcon("images/Front/17.PNG");
        ImageIcon Rattata  = new ImageIcon("images/Front/19.PNG");
        ImageIcon Raticate  = new ImageIcon("images/Front/20.PNG");
        ImageIcon Spearow  = new ImageIcon("images/Front/21.PNG");
        ImageIcon Fearow  = new ImageIcon("images/Front/22.PNG");
        ImageIcon Pikachu  = new ImageIcon("images/Front/25.PNG");
        ImageIcon Raichu  = new ImageIcon("images/Front/26.PNG");
        ImageIcon Nidoran   = new ImageIcon("images/Front/29.PNG");
        ImageIcon Nidorina  = new ImageIcon("images/Front/30.PNG");
        ImageIcon Jigglypuff  = new ImageIcon("images/Front/35.PNG");
        ImageIcon Wigglypuff  = new ImageIcon("images/ges/Front/36.PNG");
        ImageIcon Poliwag   = new ImageIcon("images/Front/61.PNG");
        ImageIcon Poliwhirl  = new ImageIcon("images/Front/62.PNG");
        ImageIcon Eevee   = new ImageIcon("images/Front/133.PNG");
        ImageIcon Vaporeon  = new ImageIcon("images/Front/134.PNG");
        ImageIcon Joelton  = new ImageIcon("images/Front/135.PNG");
        ImageIcon Flareon  = new ImageIcon("images/Front/136.PNG");
        ImageIcon Mewtwo = new ImageIcon("images/Front/150.PNG");
        ImageIcon Mew = new ImageIcon("images/Front/151.PNG");
        ImageIcon Bulbasaur_b = new ImageIcon("images/back/1.PNG");
        ImageIcon Ivysaur_b = new ImageIcon("images/back/2.PNG");
        ImageIcon Charmander_b = new ImageIcon("images/back/4.PNG");
        ImageIcon Charmeleon_b = new ImageIcon("images/back/5.PNG");
        ImageIcon Squirtle_b = new ImageIcon("images/back/7.PNG");
        ImageIcon Wartortle_b = new ImageIcon("images/back/8.PNG");
        ImageIcon Caterpie_b = new ImageIcon("images/back/10.PNG");
        ImageIcon Metapod_b = new ImageIcon("images/back/11.PNG");
        ImageIcon Weedle_b = new ImageIcon("images/back/13.PNG");
        ImageIcon Kakuna_b = new ImageIcon("images/back/14.PNG");
        ImageIcon Pidgey_b = new ImageIcon("images/back/16.PNG");
        ImageIcon Pidgeotto_b = new ImageIcon("images/back/17.PNG");
        ImageIcon Rattata_b = new ImageIcon("images/back/19.PNG");
        ImageIcon Raticate_b = new ImageIcon("images/back/20.PNG");
        ImageIcon Spearow_b = new ImageIcon("images/back/21.PNG");
        ImageIcon Fearow_b = new ImageIcon("images/back/22.PNG");
        ImageIcon Pikachu_b = new ImageIcon("images/back/25.PNG");
        ImageIcon Raichu_b = new ImageIcon("images/back/26.PNG");
        ImageIcon Nidoran_b  = new ImageIcon("images/back/29.PNG");
        ImageIcon Nidorina_b = new ImageIcon("images/back/30.PNG");
        ImageIcon Jigglypuff_b = new ImageIcon("images/back/35.PNG");
        ImageIcon Wigglypuff_b = new ImageIcon("images/back/36.PNG");
        ImageIcon Poliwag_b  = new ImageIcon("images/back/61.PNG");
        ImageIcon Poliwhirl_b = new ImageIcon("images/back/62.PNG");
        ImageIcon Eevee_b  = new ImageIcon("images/back/133.PNG");
        ImageIcon Vaporeon_b = new ImageIcon("images/back/134.PNG");
        ImageIcon Joelton_b = new ImageIcon("images/back/135.PNG");
        ImageIcon Flareon_b = new ImageIcon("images/back/136.PNG");
        ImageIcon Mewtwo_b = new ImageIcon("images/back/150.PNG");
        ImageIcon Mew_b = new ImageIcon("images/back/151.PNG");
        //flags :
        //1 = player
        //2 = komp
        nama=nama.toLowerCase();
        if(nama.equals("bulbasaur"))
        {
            if(flags==1)
            {
                g_pokemon_Sendiri.setIcon(Bulbasaur_b);
            }
            else
            {
                g_pokemon.setIcon(Bulbasaur);
            }
        }
        else if(nama.equals("ivysaur"))
        {
            if(flags==1)
            {
                g_pokemon_Sendiri.setIcon(Ivysaur_b);
            }
            else
            {
                g_pokemon.setIcon(Ivysaur);
            }
        }
        else if(nama.equals("charmander"))
        {
            if(flags==1)
            {
                System.out.println("test");
                g_pokemon_Sendiri.setIcon(Charmander_b);
            }
            else
            {
                g_pokemon.setIcon(Charmander);
            }
        }
        else if(nama.equals("charmeleon"))
        {
            if(flags==1)
            {
                g_pokemon_Sendiri.setIcon(Charmeleon_b);
            }
            else
            {
                g_pokemon.setIcon(Charmeleon);
            }
        }
        else if(nama.equals("squirtle"))
        {
            if(flags==1)
            {
                g_pokemon_Sendiri.setIcon(Squirtle_b);
            }
            else
            {
                g_pokemon.setIcon(Squirtle);
            }
        }
        else if(nama.equals("wartortle"))
        {
            if(flags==1)
            {
                g_pokemon_Sendiri.setIcon(Wartortle_b);
            }
            else
            {
                g_pokemon.setIcon(Wartortle);
            }
        }
        else if(nama.equals("caterpie"))
        {
            if(flags==1)
            {
                g_pokemon_Sendiri.setIcon(Caterpie_b);
            }
            else
            {
                g_pokemon.setIcon(Caterpie);
            }
        }
        else if(nama.equals("metapod"))
        {
            if(flags==1)
            {
                g_pokemon_Sendiri.setIcon(Metapod_b);
            }
            else
            {
                g_pokemon.setIcon(Metapod);
            }
        }
        else if(nama.equals("weedle"))
        {
            if(flags==1)
            {
                g_pokemon_Sendiri.setIcon(Weedle_b);
            }
            else
            {
                g_pokemon.setIcon(Weedle);
            }
        }
        else if(nama.equals("kakuna"))
        {
            if(flags==1)
            {
                g_pokemon_Sendiri.setIcon(Kakuna_b);
            }
            else
            {
                g_pokemon.setIcon(Kakuna);
            }
        }
        else if(nama.equals("pidgey"))
        {
            if(flags==1)
            {
                g_pokemon_Sendiri.setIcon(Pidgey_b);
            }
            else
            {
                g_pokemon.setIcon(Pidgey);
            }
        }   
        else if(nama.equals("pidgeotto"))
        {
            if(flags==1)
            {
                g_pokemon_Sendiri.setIcon(Pidgeotto_b);
            }
            else
            {
                g_pokemon.setIcon(Pidgeotto);
            }
        }   
        else if(nama.equals("rattata"))
        {
            if(flags==1)
            {
                g_pokemon_Sendiri.setIcon(Rattata_b);
            }
            else
            {
                g_pokemon.setIcon(Rattata);
            }
        }   
        else if(nama.equals("raticate"))
        {
            if(flags==1)
            {
                g_pokemon_Sendiri.setIcon(Raticate_b);
            }
            else
            {
                g_pokemon.setIcon(Raticate);
            }
        }   
        else if(nama.equals("fearow"))
        {
            if(flags==1)
            {
                g_pokemon_Sendiri.setIcon(Fearow_b);
            }
            else
            {
                g_pokemon.setIcon(Fearow);
            }
        }   
        else if(nama.equals("pikachu"))
        {
            if(flags==1)
            {
                g_pokemon_Sendiri.setIcon(Pikachu_b);
            }
            else
            {
                g_pokemon.setIcon(Pikachu);
            }
        }   
        else if(nama.equals("raichu"))
        {
            if(flags==1)
            {
                g_pokemon_Sendiri.setIcon(Raichu_b);
            }
            else
            {
                g_pokemon.setIcon(Raichu);
            }
        }   
        else if(nama.equals("nidoran"))
        {
            if(flags==1)
            {
                g_pokemon_Sendiri.setIcon(Nidoran_b);
            }
            else
            {
                g_pokemon.setIcon(Nidoran);
            }
        }   
        else if(nama.equals("nidorina"))
        {
            if(flags==1)
            {
                g_pokemon_Sendiri.setIcon(Nidorina_b);
            }
            else
            {
                g_pokemon.setIcon(Nidorina);
            }
        }   
        else if(nama.equals("jigglypuff"))
        {
            if(flags==1)
            {
                g_pokemon_Sendiri.setIcon(Jigglypuff_b);
            }
            else
            {
                g_pokemon.setIcon(Jigglypuff);
            }
        }   
        else if(nama.equals("wigglypuff"))
        {
            if(flags==1)
            {
                g_pokemon_Sendiri.setIcon(Wigglypuff_b);
            }
            else
            {
                g_pokemon.setIcon(Wigglypuff);
            }
        }   
        else if(nama.equals("poliwag"))
        {
            if(flags==1)
            {
                g_pokemon_Sendiri.setIcon(Poliwag_b);
            }
            else
            {
                g_pokemon.setIcon(Poliwag);
            }
        }   
        else if(nama.equals("poliwhirl"))
        {
            if(flags==1)
            {
                g_pokemon_Sendiri.setIcon(Poliwhirl_b);
            }
            else
            {
                g_pokemon.setIcon(Poliwhirl);
            }
        }   
        else if(nama.equals("mewtwo"))
        {
            if(flags==1)
            {
                g_pokemon_Sendiri.setIcon(Mewtwo_b);
            }
            else
            {
                g_pokemon.setIcon(Mewtwo);
            }
        }   
        else if(nama.equals("mew"))
        {
            if(flags==1)
            {
                g_pokemon_Sendiri.setIcon(Mew_b);
            }
            else
            {
                g_pokemon.setIcon(Mew);
            }
        }   
        else if(nama.equals("eevee"))
        {
            if(flags==1)
            {
                g_pokemon_Sendiri.setIcon(Eevee_b);
            }
            else
            {
                g_pokemon.setIcon(Eevee);
            }
        }   
        else if(nama.equals("vaporeon"))
        {
            if(flags==1)
            {
                g_pokemon_Sendiri.setIcon(Vaporeon);
            }
            else
            {
                g_pokemon.setIcon(Vaporeon);
            }
        }   
        else if(nama.equals("joelton"))
        {
            if(flags==1)
            {
                g_pokemon_Sendiri.setIcon(Joelton_b);
            }
            else
            {
                g_pokemon.setIcon(Joelton);
            }
        }   
        else if(nama.equals("flareon"))
        {
            if(flags==1)
            {
                g_pokemon_Sendiri.setIcon(Flareon_b);
            }
            else
            {
                g_pokemon.setIcon(Flareon);
            }
        }   
                
    }
    private void Skill()
    {
        nm_skill = mypokemon[pilihan].getSkill();
        mp_skill = mypokemon[pilihan].getMp();
        maxmp_skill = mypokemon[pilihan].getMaxmp();
    }
    private void show_skill(boolean x)
    {
        skill1.setVisible(x);
        skill2.setVisible(x);
        skill3.setVisible(x);
        skill4.setVisible(x);
    }
    private void skill_nav(boolean x)
    {
        skill.setVisible(x);
        nav.setVisible(!x);
    }
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        int press = evt.getKeyCode();
        if(i>-1)
        {
            if(pointer.getX()==304&&pointer.getY()==355)//battle skill
            {
                if(press==68)
                {
                    pointer.setLocation(430,355);
                }
                else if(press==83)
                {
                    pointer.setLocation(304,390);
                }
                else if(press==32)
                {
                    i=-1;
                    skill_nav(true);
                    show_skill(true);
                    pointer.setLocation(48,353);
                    
                } 
            }
            else if(pointer.getX()==304&&pointer.getY()==390)//pokemon
            {
                if(press==87)
                {
                    pointer.setLocation(304,355);
                }
                else if(press==68)
                {
                    pointer.setLocation(430,393);
                }
            }
            else if(pointer.getX()==430&&pointer.getY()==393)//run
            {
                if(press==65)
                {
                    pointer.setLocation(304,390);
                }
                else if(press==87)
                {
                    pointer.setLocation(430,355);
                }
            }
            else if(pointer.getX()==430&&pointer.getY()==355)//bag
            {
                if(press==65)
                {
                    pointer.setLocation(304,355);
                }
                else if(press==83)
                {
                    pointer.setLocation(430,393);
                }
            }
        }
        
        //menu1 = (48,353)
        //menu2 = (48,387)
        //menu3 = (200,387)
        //menu4 = (200,353)
        //65 =a
        //87 =w
        //68 = d
        //83 = s
        
        else if(i==-1)
        { 
            if(pointer.getX()==48&&pointer.getY()==353)//menu1
            {
                if(press==68)
                {
                    pointer.setLocation(200,353);
                }
                else if(press==83)
                {
                    pointer.setLocation(48,387);
                }
                else if(press==32)
                {
                    i=0;
                    skill_nav(false);
                    show_skill(false);
                    nav.setVisible(false);
                    g=false;
                    serang(0);
                    
                }
            }
            else if(pointer.getX()==48&&pointer.getY()==387)//menu2
            {
                if(press==68)
                {
                    pointer.setLocation(200,387);
                }
                else if(press==87)
                {
                    pointer.setLocation(48,353);
                }
                else if(press==32)
                {
                    i=0;
                    skill_nav(false);
                    show_skill(false);
                    nav.setVisible(false);
                    pointer.setLocation(304,355);
                    serang(1);
                }
            }
            else if(pointer.getX()==200&&pointer.getY()==353)//menu4
            {
                if(press==83)
                {
                    pointer.setLocation(200,387);
                }
                else if(press==65)
                {
                    pointer.setLocation(48,353);
                }
                else if(press==32)
                {
                    i=0;
                    skill_nav(false);
                    show_skill(false);
                    nav.setVisible(false);
                    pointer.setLocation(304,355);
                    serang(2);
                }
            }
            else if(pointer.getX()==200&&pointer.getY()==387)//menu3
            {
                if(press==65)
                {
                    pointer.setLocation(48,387);
                }
                else if(press==87)
                {
                    pointer.setLocation(200,353);
                }
                else if(press==32)
                {
                    i=0;
                    skill_nav(false);
                    show_skill(false);
                    nav.setVisible(false);
                    pointer.setLocation(304,355);
                    serang(3);
                    
                }
            }
            if(press==27)
            {
                System.out.println("Test");
                skill_nav(false);
                show_skill(false);
                i=0;
            }
            
        }
    }//GEN-LAST:event_formKeyPressed
    public int element(String elemen1,String elemen2,int atk)
    {
        System.out.print("Elemen "+elemen1);
        if(elemen1=="Fire")
        {
            if(elemen2=="Grass"||elemen2=="Electric")
            {
                atk*=2;
                System.out.print("Sangat Efektif");
            }
            else if(elemen2=="Water")
            {
                atk/=2;
                System.out.print("Sangat Tidak Efektif");
            }
        }
        else if(elemen1=="Water")
        {
            if(elemen2=="Fire")
            {
                atk*=2;
                System.out.print("Sangat Efektif");
            }
            else if(elemen2=="Electric"||elemen2=="Grass")
            {
                atk/=2;
                System.out.print("Sangat Tidak Efektif");
            }
        }
        else if(elemen1=="Electric")
        {
            if(elemen2=="Water"||elemen2=="Flying")
            {
                atk*=2;
                System.out.print("Sangat Efektif");
            }
            else if(elemen2=="Fire")
            {
                atk/=2;
                System.out.print("Sangat Tidak Efektif");
            }
        }
        else if(elemen1=="Grass")
        {
            if(elemen2=="Water")
            {
                atk*=2;
                System.out.print("Sangat Efektif");
            }
           else if(elemen2=="Flying"||elemen2=="Fire")
           {
               atk/=2;
               System.out.print("Sangat Tidak Efektif");
           }
        }
        else if(elemen1=="Flying")
        {
            if(elemen2=="Grass")
            {
                atk*=2;
                System.out.print("Sangat Efektif");
            }
            else if(elemen2=="Electric")
            {
                atk/=2;
                System.out.print("Sangat Tidak Efektif");
            }
        }
        System.out.println(" Dengan Element "+elemen2);
        return atk;
    }
    public void jalankan_panel(boolean x)
    {
        this.setFocusable(!x);
        if(x)
        {
            
        }
        pointer.setLocation(304,355);
        jPanel1.setVisible(false);
        jPanel1.setFocusable(false);
        back_panel.setFocusable(false);
        pointer.setVisible(true);
        kata.clear();
    }
    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
       
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        
        System.out.println("test");
    }//GEN-LAST:event_jPanel1KeyPressed

    private void back_panelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_back_panelKeyPressed
       System.out.println("Jumlah kata : "+kata.size());
       int u=0;
       int press= evt.getKeyCode();
       
        //System.out.println(kata.get(0));
            while(u<kata.size()){
                 press= evt.getKeyCode();
                nav_keterangan.setText(kata.get(0));
                if(evt.getKeyCode()==32)
                 {
                        kata.remove(0);
                        press=0;
                 }

                 press=0;
                 System.out.println("Ururtan Kata : "+u);
            }
            if(u>=kata.size())
            {
                pointer.setLocation(304,355);
                jPanel1.setVisible(false);
                jPanel1.setFocusable(false);
                back_panel.setFocusable(false);
                pointer.setVisible(true);
                kata.clear();
                jalankan_panel(false);
                skill_nav(false);
            }
        
    }//GEN-LAST:event_back_panelKeyPressed
    int now=0;
    public void serang(int i)
    {
        int atk = element(mypokemon[pilihan].getTipe(),musuh.getTipe(),mypokemon[pilihan].getAtk());
        atk = Math.abs(atk);
        musuh.setHp(musuh.getHp()-(musuh.getDef()-atk));
        float hp_sekarang = (float) hp_musuh.getValue()-Math.abs(((musuh.getDef()-atk)/(musuh.getMaxhp()/100)));
        now  = (int) Math.floor(hp_sekarang);
        System.out.println("Atk Musuh : "+(musuh.getDef()-atk));
        System.out.println("Hp Musuh : "+now);
        Thread t = new Thread()
        {
            public void run()
            {
                for (int i = hp_musuh.getValue(); i > now; i--) {
                    try {
                        Thread.sleep(20);
                        
                    } catch (InterruptedException ex) {
                        Logger.getLogger(null);
                    }
                    hp_musuh.setValue(i);
                }
            }
        };
        t.start();
        atk = element(musuh.getTipe(),mypokemon[pilihan].getTipe(),musuh.getAtk());
        atk = Math.abs(atk);
        mypokemon[pilihan].setHp(mypokemon[pilihan].getHp()-(mypokemon[pilihan].getDef()-atk));
        System.out.println("Atk Musuh : "+(mypokemon[pilihan].getDef()-atk));
        hp_sekarang = (float) hp_sendiri.getValue()-Math.abs((mypokemon[pilihan].getDef()-atk)/(mypokemon[pilihan].getMaxhp()/100));
        now  = (int) Math.floor(hp_sekarang);
        System.out.println("HP : "+now);
        Thread t2 = new Thread()
        {
            public void run()
            {
               for (int j = hp_sendiri.getValue(); j > now; j--) {
                    try {
                        Thread.sleep(20);
                        
                    } catch (InterruptedException ex) {
                        Logger.getLogger(null);
                    }
                    hp_sendiri.setValue(j);
                }
            }
        };
        
        t2.start();
        if(hp_sendiri.getValue()>25&&hp_sendiri.getValue()<=60)
        {
            hp_sendiri.setForeground(new java.awt.Color(248, 221, 62));
        }
        else if(hp_sendiri.getValue()<25)
        {
            hp_sendiri.setForeground(new java.awt.Color(248, 88, 56));
        }
        else if(hp_sendiri.getValue()>60)
        {    
            hp_sendiri.setForeground(new java.awt.Color(112, 249, 168));
        }
        if(hp_musuh.getValue()>25&&hp_musuh.getValue()<=60)
        {
            hp_musuh.setForeground(new java.awt.Color(248, 221, 62));
        }
         else if(hp_musuh.getValue()<25)
        {
             hp_musuh.setForeground(new java.awt.Color(248, 88, 56));
        }
         else if(hp_musuh.getValue()>60)
        {    
            hp_musuh.setForeground(new java.awt.Color(112, 249, 168));
        }
        if(hp_musuh.getValue()<=0){
            JOptionPane.showMessageDialog(null, "Anda Menang");
            System.exit(0);
        }
        else if(hp_sendiri.getValue()<=0){
            JOptionPane.showMessageDialog(null, "Anda Kalah");
            System.exit(0);
        }
        kata.add(mypokemon[pilihan].getNama()+" USED "+nm_skill[0]);
        kata.add(musuh.getNama()+" USED "+nm_skill[0]);
        pointer.setVisible(false);
        //jalankan_panel(true);

        pointer.setLocation(304,355);
        pointer.setVisible(true);
        skill_nav(false);
        this.setFocusable(true);
          try {
                Thread.sleep(80);
                
                gerak();

            } catch (InterruptedException ex) {
                Logger.getLogger(null);
            }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back_panel;
    private javax.swing.JLabel background;
    private javax.swing.JLabel g_pokemon;
    private javax.swing.JLabel g_pokemon_Sendiri;
    public javax.swing.JProgressBar hp_musuh;
    private javax.swing.JLabel hp_musuh_bars;
    private javax.swing.JProgressBar hp_sendiri;
    private javax.swing.JLabel hp_sendiri_bars;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel level_pokemon_sendiri;
    private javax.swing.JLabel nama_musuh;
    private javax.swing.JLabel nama_pokemon_musuh;
    private javax.swing.JLabel nama_pokemon_sendiri;
    private javax.swing.JLabel nav;
    private javax.swing.JLabel nav_keterangan;
    private javax.swing.JLabel pointer;
    private javax.swing.JLabel skill;
    private javax.swing.JLabel skill1;
    private javax.swing.JLabel skill2;
    private javax.swing.JLabel skill3;
    private javax.swing.JLabel skill4;
    private javax.swing.JLabel stats_sendiiri;
    private javax.swing.JLabel status_musuh;
    private javax.swing.JLabel tanah_lawan;
    private javax.swing.JLabel tanah_sendiri;
    // End of variables declaration//GEN-END:variables
   
}

